/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/scenes/preprocess": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preprocess */
    post: operations["preprocess_scenes_preprocess_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/objects/extract": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Extract */
    post: operations["extract_objects_extract_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/compose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compose */
    post: operations["compose_compose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/compose/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compose Preview */
    post: operations["compose_preview_compose_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update Settings
     * @description Update runtime settings and rebuild any affected clients.
     *
     *     Currently supports updating FAL_KEY. The fal client is rebuilt immediately
     *     so subsequent ML calls use the new key — no sidecar restart required.
     */
    post: operations["update_settings_settings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Receive Logs */
    post: operations["receive_logs_logs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_extract_objects_extract_post */
    Body_extract_objects_extract_post: {
      /**
       * Image
       * @description Object photo (JPEG / PNG / WEBP)
       */
      image: string;
    };
    /** Body_preprocess_scenes_preprocess_post */
    Body_preprocess_scenes_preprocess_post: {
      /**
       * Image
       * @description Room photo (JPEG / PNG / WEBP)
       */
      image: string;
    };
    /** BoundingBox */
    BoundingBox: {
      /** X */
      x: number;
      /** Y */
      y: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
    };
    /** ComposeRequest */
    ComposeRequest: {
      /** Scene Id */
      scene_id: string;
      /** Object Id */
      object_id: string;
      placement: components["schemas"]["PlacementSpec"];
      /**
       * @default {
       *       "prompt_suffix": ""
       *     }
       */
      style_hints: components["schemas"]["StyleHints"];
    };
    /** ComposeResponse */
    ComposeResponse: {
      /** Composition Id */
      composition_id: string;
      image: components["schemas"]["ComposedImage"];
    };
    /** ComposedImage */
    ComposedImage: {
      /** Url */
      url: string;
      /**
       * Content Type
       * @default image/jpeg
       */
      content_type: string;
    };
    /** DepthMap */
    DepthMap: {
      /** Url */
      url: string;
      /** Width */
      width: number;
      /** Height */
      height: number;
    };
    /** ExtractResponse */
    ExtractResponse: {
      /** Object Id */
      object_id: string;
      masked: components["schemas"]["ExtractedObject"];
    };
    /** ExtractedObject */
    ExtractedObject: {
      /** Url */
      url: string;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /**
       * Content Type
       * @default image/png
       */
      content_type: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** LogEntry */
    LogEntry: {
      level: components["schemas"]["LogLevel"];
      /** Message */
      message: string;
      /** Correlation Id */
      correlation_id: string;
      /** Timestamp */
      timestamp: string;
      /**
       * Context
       * @default {}
       */
      context: {
        [key: string]: unknown;
      };
    };
    /**
     * LogLevel
     * @enum {string}
     */
    LogLevel: "debug" | "info" | "warn" | "error";
    /** LogRequest */
    LogRequest: {
      /** Entries */
      entries: components["schemas"]["LogEntry"][];
    };
    /** MaskResult */
    MaskResult: {
      /** Url */
      url: string;
      /**
       * Label
       * @default
       */
      label: string;
      /**
       * Score
       * @default 0
       */
      score: number;
      /**
       * Area
       * @default 0
       */
      area: number;
      /**
       * Bbox
       * @default []
       */
      bbox: number[];
    };
    /** PlacementSpec */
    PlacementSpec: {
      bbox: components["schemas"]["BoundingBox"];
      /**
       * Depth Hint
       * @default 0.5
       */
      depth_hint: number;
      /**
       * Rotation
       * @default 0
       */
      rotation: number;
    };
    /** PreprocessResponse */
    PreprocessResponse: {
      /** Scene Id */
      scene_id: string;
      depth_map: components["schemas"]["DepthMap"];
      /** Masks */
      masks: components["schemas"]["MaskResult"][];
      metadata: components["schemas"]["SceneMetadata"];
    };
    /** PreviewComposeResponse */
    PreviewComposeResponse: {
      /** Preview Id */
      preview_id: string;
      image: components["schemas"]["ComposedImage"];
    };
    /** SceneMetadata */
    SceneMetadata: {
      /** Dominant Surface */
      dominant_surface: string;
      /** Lighting Hint */
      lighting_hint: string;
      /** Light Direction */
      light_direction: string;
      /** Color Temperature */
      color_temperature: string;
    };
    /** StyleHints */
    StyleHints: {
      /**
       * Prompt Suffix
       * @default
       */
      prompt_suffix: string;
    };
    /** UpdateSettingsRequest */
    UpdateSettingsRequest: {
      /** Fal Key */
      fal_key?: string | null;
    };
    /** UpdateSettingsResponse */
    UpdateSettingsResponse: {
      /** Ok */
      ok: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  preprocess_scenes_preprocess_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_preprocess_scenes_preprocess_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreprocessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  extract_objects_extract_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_extract_objects_extract_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExtractResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compose_compose_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComposeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComposeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compose_preview_compose_preview_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComposeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreviewComposeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_settings_settings_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSettingsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateSettingsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  receive_logs_logs_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
